In [86]:
import pandas as pd

In [87]:
df = pd.read_csv("IMDB-Movie-Dataset(2023-1951).csv")
df.head()

,Unnamed: 0,movie_id,movie_name,year,genre,overview,director,cast
0,0,tt15354916,Jawan,2023,"Action, Thriller",A high-octane action thriller which outlines t...,Atlee,"Shah Rukh Khan, Nayanthara, Vijay Sethupathi, ..."
1,1,tt15748830,Jaane Jaan,2023,"Crime, Drama, Mystery",A single mother and her daughter who commit a ...,Sujoy Ghosh,"Kareena Kapoor, Jaideep Ahlawat, Vijay Varma, ..."
2,2,tt11663228,Jailer,2023,"Action, Comedy, Crime",A retired jailer goes on a manhunt to find his...,Nelson Dilipkumar,"Rajinikanth, Mohanlal, Shivarajkumar, Jackie S..."
3,3,tt14993250,Rocky Aur Rani Kii Prem Kahaani,2023,"Comedy, Drama, Family",Flamboyant Punjabi Rocky and intellectual Beng...,Karan Johar,"Ranveer Singh, Alia Bhatt, Dharmendra, Shabana..."
4,4,tt15732324,OMG 2,2023,"Comedy, Drama",An unhappy civilian asks the court to mandate ...,Amit Rai,"Pankaj Tripathi, Akshay Kumar, Yami Gautam, Pa..."

In [88]:
df = df.merge(credits, on="movie_name")

TypeError: Can only merge Series or DataFrame objects, a <class '_sitebuiltins._Printer'> was passed

In [89]:
# print(df['genre'])

def convert_genre(genre_str):
    list = genre_str.split(", ")
    return list

df['genre'] = df['genre'].apply(convert_genre)

print(df['genre'])

0              [Action, Thriller]
1         [Crime, Drama, Mystery]
2         [Action, Comedy, Crime]
3         [Comedy, Drama, Family]
4                 [Comedy, Drama]
                  ...
2194                   [Thriller]
2195    [Drama, Musical, Romance]
2196           [Musical, Romance]
2197     [Drama, Family, Fantasy]
2198      [Action, Comedy, Drama]
Name: genre, Length: 2199, dtype: object

In [90]:
df['overview'] = df['overview'].apply(lambda x: x.split(" "))

df.head()

,Unnamed: 0,movie_id,movie_name,year,genre,overview,director,cast
0,0,tt15354916,Jawan,2023,"[Action, Thriller]","[A, high-octane, action, thriller, which, outl...",Atlee,"Shah Rukh Khan, Nayanthara, Vijay Sethupathi, ..."
1,1,tt15748830,Jaane Jaan,2023,"[Crime, Drama, Mystery]","[A, single, mother, and, her, daughter, who, c...",Sujoy Ghosh,"Kareena Kapoor, Jaideep Ahlawat, Vijay Varma, ..."
2,2,tt11663228,Jailer,2023,"[Action, Comedy, Crime]","[A, retired, jailer, goes, on, a, manhunt, to,...",Nelson Dilipkumar,"Rajinikanth, Mohanlal, Shivarajkumar, Jackie S..."
3,3,tt14993250,Rocky Aur Rani Kii Prem Kahaani,2023,"[Comedy, Drama, Family]","[Flamboyant, Punjabi, Rocky, and, intellectual...",Karan Johar,"Ranveer Singh, Alia Bhatt, Dharmendra, Shabana..."
4,4,tt15732324,OMG 2,2023,"[Comedy, Drama]","[An, unhappy, civilian, asks, the, court, to, ...",Amit Rai,"Pankaj Tripathi, Akshay Kumar, Yami Gautam, Pa..."

In [91]:
def convert_director(director_str):
    list = director_str.split(", ")
    return list

df['director'] = df['director'].apply(convert_director)
df.head()

,Unnamed: 0,movie_id,movie_name,year,genre,overview,director,cast
0,0,tt15354916,Jawan,2023,"[Action, Thriller]","[A, high-octane, action, thriller, which, outl...",[Atlee],"Shah Rukh Khan, Nayanthara, Vijay Sethupathi, ..."
1,1,tt15748830,Jaane Jaan,2023,"[Crime, Drama, Mystery]","[A, single, mother, and, her, daughter, who, c...",[Sujoy Ghosh],"Kareena Kapoor, Jaideep Ahlawat, Vijay Varma, ..."
2,2,tt11663228,Jailer,2023,"[Action, Comedy, Crime]","[A, retired, jailer, goes, on, a, manhunt, to,...",[Nelson Dilipkumar],"Rajinikanth, Mohanlal, Shivarajkumar, Jackie S..."
3,3,tt14993250,Rocky Aur Rani Kii Prem Kahaani,2023,"[Comedy, Drama, Family]","[Flamboyant, Punjabi, Rocky, and, intellectual...",[Karan Johar],"Ranveer Singh, Alia Bhatt, Dharmendra, Shabana..."
4,4,tt15732324,OMG 2,2023,"[Comedy, Drama]","[An, unhappy, civilian, asks, the, court, to, ...",[Amit Rai],"Pankaj Tripathi, Akshay Kumar, Yami Gautam, Pa..."

In [92]:
def convert_cast(casts):
    list = casts.split(", ")
    return list

df['cast'] = df['cast'].apply(convert_cast)

df.head()

,Unnamed: 0,movie_id,movie_name,year,genre,overview,director,cast
0,0,tt15354916,Jawan,2023,"[Action, Thriller]","[A, high-octane, action, thriller, which, outl...",[Atlee],"[Shah Rukh Khan, Nayanthara, Vijay Sethupathi,..."
1,1,tt15748830,Jaane Jaan,2023,"[Crime, Drama, Mystery]","[A, single, mother, and, her, daughter, who, c...",[Sujoy Ghosh],"[Kareena Kapoor, Jaideep Ahlawat, Vijay Varma,..."
2,2,tt11663228,Jailer,2023,"[Action, Comedy, Crime]","[A, retired, jailer, goes, on, a, manhunt, to,...",[Nelson Dilipkumar],"[Rajinikanth, Mohanlal, Shivarajkumar, Jackie ..."
3,3,tt14993250,Rocky Aur Rani Kii Prem Kahaani,2023,"[Comedy, Drama, Family]","[Flamboyant, Punjabi, Rocky, and, intellectual...",[Karan Johar],"[Ranveer Singh, Alia Bhatt, Dharmendra, Shaban..."
4,4,tt15732324,OMG 2,2023,"[Comedy, Drama]","[An, unhappy, civilian, asks, the, court, to, ...",[Amit Rai],"[Pankaj Tripathi, Akshay Kumar, Yami Gautam, P..."

In [93]:
df.head()

,Unnamed: 0,movie_id,movie_name,year,genre,overview,director,cast
0,0,tt15354916,Jawan,2023,"[Action, Thriller]","[A, high-octane, action, thriller, which, outl...",[Atlee],"[Shah Rukh Khan, Nayanthara, Vijay Sethupathi,..."
1,1,tt15748830,Jaane Jaan,2023,"[Crime, Drama, Mystery]","[A, single, mother, and, her, daughter, who, c...",[Sujoy Ghosh],"[Kareena Kapoor, Jaideep Ahlawat, Vijay Varma,..."
2,2,tt11663228,Jailer,2023,"[Action, Comedy, Crime]","[A, retired, jailer, goes, on, a, manhunt, to,...",[Nelson Dilipkumar],"[Rajinikanth, Mohanlal, Shivarajkumar, Jackie ..."
3,3,tt14993250,Rocky Aur Rani Kii Prem Kahaani,2023,"[Comedy, Drama, Family]","[Flamboyant, Punjabi, Rocky, and, intellectual...",[Karan Johar],"[Ranveer Singh, Alia Bhatt, Dharmendra, Shaban..."
4,4,tt15732324,OMG 2,2023,"[Comedy, Drama]","[An, unhappy, civilian, asks, the, court, to, ...",[Amit Rai],"[Pankaj Tripathi, Akshay Kumar, Yami Gautam, P..."

In [94]:
df['genre'] = df['genre'].apply(lambda x: [i.replace(" ","") for i in x])
df['cast'] = df['cast'].apply(lambda x: [i.replace(" ","") for i in x])
df['director'] = df['director'].apply(lambda x: [i.replace(" ","") for i in x])

df.head()

,Unnamed: 0,movie_id,movie_name,year,genre,overview,director,cast
0,0,tt15354916,Jawan,2023,"[Action, Thriller]","[A, high-octane, action, thriller, which, outl...",[Atlee],"[ShahRukhKhan, Nayanthara, VijaySethupathi, De..."
1,1,tt15748830,Jaane Jaan,2023,"[Crime, Drama, Mystery]","[A, single, mother, and, her, daughter, who, c...",[SujoyGhosh],"[KareenaKapoor, JaideepAhlawat, VijayVarma, Sa..."
2,2,tt11663228,Jailer,2023,"[Action, Comedy, Crime]","[A, retired, jailer, goes, on, a, manhunt, to,...",[NelsonDilipkumar],"[Rajinikanth, Mohanlal, Shivarajkumar, JackieS..."
3,3,tt14993250,Rocky Aur Rani Kii Prem Kahaani,2023,"[Comedy, Drama, Family]","[Flamboyant, Punjabi, Rocky, and, intellectual...",[KaranJohar],"[RanveerSingh, AliaBhatt, Dharmendra, ShabanaA..."
4,4,tt15732324,OMG 2,2023,"[Comedy, Drama]","[An, unhappy, civilian, asks, the, court, to, ...",[AmitRai],"[PankajTripathi, AkshayKumar, YamiGautam, Pawa..."

In [96]:
df['genre'] = df['genre'].apply(lambda x: [i.lower() for i in x])
df['cast'] = df['cast'].apply(lambda x: [i.lower() for i in x])
df['director'] = df['director'].apply(lambda x: [i.lower() for i in x])
df['overview'] = df['overview'].apply(lambda x: [i.lower() for i in x])
df['year'] = df['year'].apply(lambda x: str(x)).apply(lambda x: x.split(" "))



df.head()

,Unnamed: 0,movie_id,movie_name,year,genre,overview,director,cast
0,0,tt15354916,Jawan,[2023],"[action, thriller]","[a, high-octane, action, thriller, which, outl...",[atlee],"[shahrukhkhan, nayanthara, vijaysethupathi, de..."
1,1,tt15748830,Jaane Jaan,[2023],"[crime, drama, mystery]","[a, single, mother, and, her, daughter, who, c...",[sujoyghosh],"[kareenakapoor, jaideepahlawat, vijayvarma, sa..."
2,2,tt11663228,Jailer,[2023],"[action, comedy, crime]","[a, retired, jailer, goes, on, a, manhunt, to,...",[nelsondilipkumar],"[rajinikanth, mohanlal, shivarajkumar, jackies..."
3,3,tt14993250,Rocky Aur Rani Kii Prem Kahaani,[2023],"[comedy, drama, family]","[flamboyant, punjabi, rocky, and, intellectual...",[karanjohar],"[ranveersingh, aliabhatt, dharmendra, shabanaa..."
4,4,tt15732324,OMG 2,[2023],"[comedy, drama]","[an, unhappy, civilian, asks, the, court, to, ...",[amitrai],"[pankajtripathi, akshaykumar, yamigautam, pawa..."

In [100]:
df['tag'] = df['year'] + df['genre']+df['overview']+df['director']+df['cast'] 
df['tag'] = df['tag'].apply(lambda x: " ".join(x))

print(df['tag'])

0       2023 action thriller a high-octane action thri...
1       2023 crime drama mystery a single mother and h...
2       2023 action comedy crime a retired jailer goes...
3       2023 comedy drama family flamboyant punjabi ro...
4       2023 comedy drama an unhappy civilian asks the...
                              ...
2194    nan thriller add a plot subhashghai shatrughan...
2195    2002 drama musical romance a renowned music te...
2196    2021 musical romance when a ballroom dancer's ...
2197    1989 drama family fantasy after the tragic dea...
2198    2001 action comedy drama raj is a successful l...
Name: tag, Length: 2199, dtype: object

In [104]:
# ! pip install nltk
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [106]:
def stem_words(text):
    list =[]
    for ele in text.split(" "):
        list.append(ps.stem(ele))
    return " ".join(list)

df['tag'].apply(stem_words)
df['tag']

0       2023 action thriller a high-octane action thri...
1       2023 crime drama mystery a single mother and h...
2       2023 action comedy crime a retired jailer goes...
3       2023 comedy drama family flamboyant punjabi ro...
4       2023 comedy drama an unhappy civilian asks the...
                              ...
2194    nan thriller add a plot subhashghai shatrughan...
2195    2002 drama musical romance a renowned music te...
2196    2021 musical romance when a ballroom dancer's ...
2197    1989 drama family fantasy after the tragic dea...
2198    2001 action comedy drama raj is a successful l...
Name: tag, Length: 2199, dtype: object

In [111]:
! pip install scikit-learn

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words='english')

WARNING: Skipping sklearn as it is not installed.

Defaulting to user installation because normal site-packages is not writeable
Collecting scikit-learn
  Downloading scikit_learn-1.5.0-cp312-cp312-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.19.5 in c:\users\fatima\appdata\roaming\python\python312\site-packages (from scikit-learn) (1.26.4)
Collecting scipy>=1.6.0 (from scikit-learn)
  Downloading scipy-1.13.1-cp312-cp312-win_amd64.whl.metadata (60 kB)
     ---------------------------------------- 0.0/60.6 kB ? eta -:--:--
     ---------------------------------------- 0.0/60.6 kB ? eta -:--:--
     ------------------- ------------------ 30.7/60.6 kB 660.6 kB/s eta 0:00:01
     -------------------------------------- 60.6/60.6 kB 811.9 kB/s eta 0:00:00
Requirement already satisfied: joblib>=1.2.0 in c:\users\fatima\appdata\roaming\python\python312\site-packages (from scikit-learn) (1.4.2)
Collecting threadpoolctl>=3.1.0 (from scikit-learn)
  Downloading threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.5.0-cp312-cp312-win_amd64.whl (10.9 MB)
   ---------------------------------------- 0.0/10.9 MB ? eta -:--:--
   --- ------------------------------------ 1.0/10.9 MB 22.0 MB/s eta 0:00:01
   ----------- ---------------------------- 3.2/10.9 MB 49.9 MB/s eta 0:00:01
   ---------------------- ----------------- 6.1/10.9 MB 49.1 MB/s eta 0:00:01
   -------------------------------- ------- 8.8/10.9 MB 46.8 MB/s eta 0:00:01
   ------------------------------------- -- 10.1/10.9 MB 43.3 MB/s eta 0:00:01
   ---------------------------------------  10.8/10.9 MB 40.9 MB/s eta 0:00:01
   ---------------------------------------- 10.9/10.9 MB 36.2 MB/s eta 0:00:00
Downloading scipy-1.13.1-cp312-cp312-win_amd64.whl (45.9 MB)
   ---------------------------------------- 0.0/45.9 MB ? eta -:--:--
    --------------------------------------- 0.8/45.9 MB 17.2 MB/s eta 0:00:03
   - -------------------------------------- 1.5/45.9 MB 16.1 MB/s eta 0:00:03
   - -------------------------------------- 2.2/45.9 MB 15.9 MB/s eta 0:00:03
   -- ------------------------------------- 3.0/45.9 MB 15.9 MB/s eta 0:00:03
   --- ------------------------------------ 3.8/45.9 MB 16.2 MB/s eta 0:00:03
   ---- ----------------------------------- 4.6/45.9 MB 16.5 MB/s eta 0:00:03
   ---- ----------------------------------- 5.5/45.9 MB 16.7 MB/s eta 0:00:03
   ----- ---------------------------------- 6.2/45.9 MB 16.6 MB/s eta 0:00:03
   ------ --------------------------------- 7.0/45.9 MB 16.6 MB/s eta 0:00:03
   ------ --------------------------------- 7.9/45.9 MB 16.9 MB/s eta 0:00:03
   ------- -------------------------------- 8.8/45.9 MB 17.0 MB/s eta 0:00:03
   -------- ------------------------------- 9.6/45.9 MB 17.0 MB/s eta 0:00:03
   --------- ------------------------------ 10.5/45.9 MB 16.8 MB/s eta 0:00:03
   --------- ------------------------------ 11.3/45.9 MB 17.2 MB/s eta 0:00:03
   ---------- ----------------------------- 12.1/45.9 MB 17.2 MB/s eta 0:00:02
   ----------- ---------------------------- 13.0/45.9 MB 17.7 MB/s eta 0:00:02
   ------------ --------------------------- 13.9/45.9 MB 17.7 MB/s eta 0:00:02
   ------------ --------------------------- 14.8/45.9 MB 18.2 MB/s eta 0:00:02
   ------------- -------------------------- 15.8/45.9 MB 18.2 MB/s eta 0:00:02
   -------------- ------------------------- 16.8/45.9 MB 18.7 MB/s eta 0:00:02
   --------------- ------------------------ 17.8/45.9 MB 19.3 MB/s eta 0:00:02
   ---------------- ----------------------- 18.8/45.9 MB 19.3 MB/s eta 0:00:02
   ----------------- ---------------------- 19.8/45.9 MB 19.8 MB/s eta 0:00:02
   ------------------ --------------------- 20.8/45.9 MB 19.8 MB/s eta 0:00:02
   ------------------ --------------------- 21.8/45.9 MB 20.5 MB/s eta 0:00:02
   ------------------- -------------------- 22.8/45.9 MB 20.5 MB/s eta 0:00:02
   -------------------- ------------------- 23.8/45.9 MB 21.1 MB/s eta 0:00:02
   --------------------- ------------------ 24.9/45.9 MB 21.1 MB/s eta 0:00:01
   ---------------------- ----------------- 25.9/45.9 MB 21.8 MB/s eta 0:00:01
   ----------------------- ---------------- 27.1/45.9 MB 21.8 MB/s eta 0:00:01
   ------------------------ --------------- 28.1/45.9 MB 21.8 MB/s eta 0:00:01
   ------------------------- -------------- 29.2/45.9 MB 22.6 MB/s eta 0:00:01
   -------------------------- ------------- 30.4/45.9 MB 22.6 MB/s eta 0:00:01
   --------------------------- ------------ 31.5/45.9 MB 22.5 MB/s eta 0:00:01
   ---------------------------- ----------- 32.7/45.9 MB 23.4 MB/s eta 0:00:01
   ----------------------------- ---------- 33.9/45.9 MB 24.2 MB/s eta 0:00:01
   ------------------------------ --------- 34.9/45.9 MB 23.4 MB/s eta 0:00:01
   ------------------------------- -------- 36.2/45.9 MB 24.2 MB/s eta 0:00:01
   -------------------------------- ------- 37.4/45.9 MB 25.2 MB/s eta 0:00:01
   --------------------------------- ------ 38.5/45.9 MB 25.2 MB/s eta 0:00:01
   ---------------------------------- ----- 39.6/45.9 MB 25.1 MB/s eta 0:00:01
   ----------------------------------- ---- 40.8/45.9 MB 25.1 MB/s eta 0:00:01
   ------------------------------------ --- 42.1/45.9 MB 25.2 MB/s eta 0:00:01
   ------------------------------------- -- 43.4/45.9 MB 26.2 MB/s eta 0:00:01
   -------------------------------------- - 44.7/45.9 MB 26.2 MB/s eta 0:00:01
   ---------------------------------------  45.9/45.9 MB 26.2 MB/s eta 0:00:01
   ---------------------------------------  45.9/45.9 MB 26.2 MB/s eta 0:00:01
   ---------------------------------------  45.9/45.9 MB 26.2 MB/s eta 0:00:01
   ---------------------------------------- 45.9/45.9 MB 20.4 MB/s eta 0:00:00
Downloading threadpoolctl-3.5.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, scikit-learn
Successfully installed scikit-learn-1.5.0 scipy-1.13.1 threadpoolctl-3.5.0

In [112]:
vectors = cv.fit_transform(df['tag']).toarray()

In [113]:
cv.get_feature_names_out()

array(['000', '10', '100', ..., 'zoyaakhtar', 'zoyahussain', 'zubairkhan'],
      dtype=object)

In [114]:
from sklearn.metrics.pairwise import cosine_similarity

In [115]:
similarity_vector = cosine_similarity(vectors)

In [120]:
def recommend(movie):
    movie_index = df[df['movie_name'] == movie].index[0]
    distances = similarity_vector[movie_index]
    moivie_list = sorted(list(enumerate(distances)),reverse=True,key = lambda x:x[1])[1:6]

    for i in moivie_list:
        print(df.iloc[i[0]].movie_name)

recommend('Pathaan')

War
Jawan
Fighter
Tiger 3
Tariq

In [121]:
import pickle

In [122]:
pickle.dump(df,open('movie_list.pkl','wb'))
pickle.dump(similarity_vector,open('similarity.pkl','wb'))